### ISSUE TITLE
Do you accept remote people?

### ISSUE THREAD

**Issue by haikyuu** [entria/vagas#1]

**Comment by rturk** [comment]
Hi @haikyuu you can work remote, but first you need to work at least 3-4 months with us so you can get in par with our code.

**Comment by haikyuu** [comment]
OK thanks. And about the language, is it ok if i only talk english?

**Comment by lucasbento** [comment]
@haikyuu: definitely, we all speak english. :)

**Comment by haikyuu** [comment]
Sounds cool ✨

**Comment by sibelius** [comment]
we do now: https://github.com/entria/jobs/pull/2
